---
- hosts: [mesos_masters]
  sudo: True

  pre_tasks:
  - name: "Build hosts file"
    lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}" state=present
    when: hostvars[item].ansible_default_ipv4.address is defined
    with_items: groups['all']
    tags: hosts

  roles:
    - common-mesos
    - { role: 'ansible-java8', tags:['runtimes', 'java'], when: ansible_os_family == 'Debian' }
    - { role: 'ansible-zookeeper', zookeeper_hosts: "{{ groups.mesos_masters}}", tags:['zookeeper'] }
    - { role: 'ansible-mesos', mesos_quorum: "2", zookeeper_hostnames: "{{ groups.mesos_masters | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}", mesos_install_mode: 'master', mesos_cluster_name: 'mlh_mesos', tags: ['mesos', 'platforms'] }
    - { role: 'ansible-marathon', zookeeper_hostnames: "{{ groups.mesos_masters | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}",  tags:['mesos-tools'] }
    - { role: 'ansible-consul', consul_client_address: "0.0.0.0",  consul_version: "0.4.1", consul_datacenter: "sea", consul_is_server: true, consul_servers: "{{ groups.mesos_masters  }}", consul_is_ui: true, consul_join_at_start: true }


- hosts: [mesos_workers]
  sudo: True

  pre_tasks:
  - name: "Build hosts file"
    lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}" state=present
    when: hostvars[item].ansible_default_ipv4.address is defined
    with_items: groups['all']
    tags: hosts

  roles:
    - common-mesos
    - { role: 'ansible-docker', tags:['docker'] }
    - { role: 'ansible-java8', tags:['java'], when: ansible_os_family == 'Debian' }
    - { role: 'ansible-mesos', mesos_containerizers: "docker,mesos", zookeeper_hostnames: "{{ groups.mesos_masters | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}",  mesos_install_mode: "slave", tags: ['mesos'] }
    - { role: 'ansible-consul', consul_version: "0.4.1", consul_client_address: "0.0.0.0", consul_is_server: false, consul_datacenter: "sea", consul_servers: "{{ groups.mesos_masters }}", consul_join_at_start: true, tags:['consul'] }

